language: ruby
cache: bundler
before_install:
  - gem install bundler
  - gem install rake
#script:
#  - bundle exec jekyll serve
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master
rvm:
 - 2.4
